import numpy as np
import itertools

# CSR storage
class Csr:
    m_ndims = np.empty(0, dtype=int) 
    m_coalesc_idx = np.empty(0, dtype=int) 
    m_idx = np.empty((0, 0), dtype=int) 
    m_values = np.empty(0, dtype=np.double)

    def __init__(self, ndims):
        self.m_ndims = np.array(ndims, dtype=int) 
        self.m_coalesc_idx = np.zeros(1, dtype=int)
        self.m_idx = np.empty((0, len(ndims)-1), dtype=int)
        self.m_values = np.empty(0, dtype=np.double)

    def copy_construct(self, ndims, coalesc_idx, idx, values):
        self.m_ndims = np.array(ndims) 
        self.m_coalesc_idx = coalesc_idx
        self.m_idx = idx
        self.m_values = np.array(values) 
    
    def append_dense(self, dense, **kwargs):
        idx = np.array(np.nonzero(dense))
        self.m_ndims[kwargs.get('axis', None)] = self.m_ndims[kwargs.get('axis', None)]+1
        self.m_coalesc_idx = np.append(self.m_coalesc_idx, self.m_coalesc_idx[-1]+idx.shape[1])
        self.m_idx = np.append(self.m_idx, np.transpose(idx), axis=0)
        self.m_values = np.append(self.m_values, dense[tuple(idx)])

    """
    def append_csr(self, csr, **kwargs):
        self.m_ndims[kwargs.get('axis', None)] = self.m_ndims[kwargs.get('axis', None)]+1
        
        self.m_coalesc_idx = np.append(self.m_coalesc_idx, self.m_coalesc_idx[-1]+csr.m_coalesc_idx)
        self.m_idx = np.append(self.m_idx, csr.m_idx, axis=0)
        self.m_values = np.append(self.m_values, csr.m_values)
    """

    # /!\ support only coalescent axis
    def get(self, id, **kwargs):
        ndims = np.copy(self.m_ndims)
        ndims[kwargs.get('axis', None)] = 1
        csr = Csr(ndims)
        csr.copy_construct(ndims, np.array([0, self.m_coalesc_idx[id+1]-self.m_coalesc_idx[id]]), np.array([self.m_idx[i,:] for i in range(self.m_coalesc_idx[id], self.m_coalesc_idx[id+1])]), np.array([self.m_values[i] for i in range(self.m_coalesc_idx[id], self.m_coalesc_idx[id+1])]))
        return csr 

    # /!\ untested for non-coalescent axis
    def mult(self, x, **kwargs):
        operate_on = kwargs.get('operate_on', None);
        axis_left = list(np.arange(0, len(x.shape)) if operate_on=="left" else np.arange(0, len(self.m_ndims)-len(x.shape))) # in practice this is just list(0)
        # TODO: assert axis_left rank being one
        axis_right = [ax for ax in list(np.arange(0, len(self.m_ndims))) if ax not in axis_left]
        axis_prod = axis_left if operate_on=="left" else axis_right
        axis_ortho = axis_right if operate_on=="left" else axis_left
        prod = np.zeros(self.m_ndims[axis_ortho])
        for coalesc_id_id in range(0, len(self.m_coalesc_idx)-1):
            id_left = (coalesc_id_id,);
            for k in range(self.m_coalesc_idx[coalesc_id_id], self.m_coalesc_idx[coalesc_id_id+1]):
                id_right = tuple(self.m_idx[k,:].astype(int));
                id_prod = id_left if operate_on=="left" else id_right
                id_ortho = id_right if operate_on=="left" else id_left
                prod[id_ortho] = prod[id_ortho] + x[id_prod]*self.m_values[k]
        return prod
                
def csr2dense(csr):
    dense = np.zeros(csr.m_ndims);
    for coalesc_id_id in range(0, len(csr.m_coalesc_idx)-1):
        for i in range(csr.m_coalesc_idx[coalesc_id_id], csr.m_coalesc_idx[coalesc_id_id+1]):
            dense[(csr.m_coalesc_idx[coalesc_id_id],) + tuple([int(csr.m_idx[i, j]) for j in range(0,len(csr.m_ndims)-1)])] = csr.m_values[i]
    return dense


# General Tensor class with internal symmetries
class Tensor:
    m_r = 0
    m_d = 0
    m_U = Csr((0,)) 
    m_V = Csr((0,)) 
    m_data = np.empty(0) 

    # Gram-shmidt approach to produce from vec an orthogonal vector to the vector space generated by basis
    def orthogonalize(self, vec, basis):
        for i in range(0,basis.m_ndims[0]):
            eigentensor = csr2dense(basis.get(i, axis=0)).reshape(self.m_d,self.m_d)
            vec = vec - np.tensordot(vec, eigentensor)/np.tensordot(eigentensor, eigentensor)*eigentensor
        return vec

    # Build orthonormal basis for the eigen subspace associated to the eigenvalue 1 of the projection operator
    def orthonormal_basis_subspace_eigenvalue_1(self, Proj):
        U = Csr((0,self.m_d,self.m_d)); 
        V = Csr((0,self.m_d,self.m_d)); 

        index = 0;
        # while np.size(V, axis=2)<d*(d+1)//2:
        while V.m_ndims[0]<self.m_d*(self.m_d-1)//2: # TODO: general formula
            index = index+1;
            candidate = np.zeros((self.m_d, self.m_d))
            for i in range(0,self.m_d):
                for j in range(0,self.m_d):
                    candidate[i,j] = index//2**(i*self.m_d+j)%2
            # candidate = np.tensordot(Proj, np.random.randint(2, size=(d,d)));
            v = self.orthogonalize(np.tensordot(Proj, candidate), V);

            if np.any(v>0.25):
                v = v/np.sqrt(np.tensordot(v, v)) # normalize
                u = np.tensordot(np.tensordot(Tr, Proj), v) # not sure if this or u = v is correct
                # u = v 
                U.append_dense(u.reshape(self.m_d,self.m_d), axis=0)
                V.append_dense(v.reshape(self.m_d,self.m_d), axis=0)
        return [U, V] 

    def __init__(self, Proj):
        # TODO: assert Proj hypercubic and pair rank
        self.m_r = len(Proj.shape)//2
        self.m_d = Proj.shape[0]
        [self.m_U, self.m_V] = self.orthonormal_basis_subspace_eigenvalue_1(Proj)

    def __call__(self):
        return self.m_V.mult(self.m_data, operate_on="left") 

    def set(self, x):
        self.m_data = self.m_U.mult(x, operate_on="right") 

# Projector filler
def fill(T, idx, lambda_func):
    r = len(T.shape)
    d = T.shape[0]
    for i in range(0,d):
        new_idx = idx + (i,)
        if len(new_idx)==r:
            lambda_func(T, new_idx)
        else:
            fill(T, new_idx, lambda_func)

def I_lambda(T, idx):
    if idx[0]==idx[2] and idx[1]==idx[3]:
        T[idx] = 1

def Tr_lambda(T, idx):
    if idx[0]==idx[3] and idx[1]==idx[2]:
        T[idx] = 1


# main
d = 4 # dimension

# Create rank-2 identity operator
I = np.zeros((d, d, d, d))
fill(I, (), I_lambda)

# Create rank-2 transpose operator
Tr = np.zeros((d, d, d, d))
fill(Tr, (), Tr_lambda)

# Create symmetric projection
Sym = (Tr+I)/2

# Create antisymmetric projection
AntiSym = (Tr-I)/2 

#test
tensor = Tensor(AntiSym)

test = np.empty((d,d))

for i in range(0,d):
    for j in range(0,d):
        test[i,j] = j-i
print(test)

tensor.set(test)
uncompressed_test = tensor()
print(np.all(abs(uncompressed_test-test)<1e-14))
